### PR TITLE
Switch bundled font file type from woff to woff2

### LINKED ISSUE #1002: Fix Google Font font downloading
In https://github.com/rstudio/bslib/pull/983 I "fixed" Google Font downloading, but the fonts have been unstable over the last month. It seems that the new endpoints return slightly different font files and that the version of the font URL used by Google is not deterministic -- possibly Google is slowly rolling out changes?

The results from https://rstudio.github.io/shinycoreci/results/2024/03/11/ show that will likely need to get to the bottom of the changes before releasing v0.7.0.

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #1002 (at least partially)

This PR should fix the "constantly updating" font files mentioned in #1002 by switching from `woff` to `woff2`. The difference in [browser support](https://caniuse.com/?search=woff) nowadays is barely noticeable (97.98% vs 97.32%). Essentially the only difference is a drop of IE11 support, which Bootstrap 5 has officially dropped. As an additional benefit, the compression of the font files should be much better with woff2.

As a technical note, the font file downloading script (`tools/download_preset_files.R`) sets the `User-Agent` when requesting files to a modern version of Chrome, just to let Google Fonts know that we'd like `woff2` (surprisingly, there doesn't seem to be any other way to do this). It's worth noting that [`sass:::read_gfont_url`](https://github.com/rstudio/sass/blob/ae93a9a9dae17f5cf10ed1ddd556ab08ae96b485/R/fonts.R#L464-L475) does something similar to get `woff` files. We may want to consider updating the User-Agent there as well, but I'm a bit skeptical the other issues we've been seeing would be fixed by that.

### CODE REVIEW

**Comment by cpsievert** [comment]
I think the failures here will have to be fixed by `schloerke/shiny-workflows` by pulling in the latest `setup-r-dependencies@v2` fix pandoc installation

https://github.com/r-lib/actions/releases/tag/v2
https://github.com/rstudio/shiny-workflows/blob/main/setup-r-package/action.yaml#L81-L83

**Comment by gadenbuie** [comment]
I was a little worried about the number of changed files. It turns out the number of font files has gone up quite a bit, but the overall size is somewhat smaller.

### Before

```bash
ls -l inst/fonts | grep "^-" | wc -l
#> 70
```

```
* checking installed package size ... NOTE
  installed size is 12.7Mb
  sub-directories of 1Mb or more:
    components   1.0Mb
    fonts        3.7Mb
    lib          5.4Mb
```

### After

```bash
ls -l inst/fonts | grep "^-" | wc -l
#> 151
```

```
* checking installed package size ... NOTE
  installed size is 12.2Mb
  sub-directories of 1Mb or more:
    components   1.0Mb
    fonts        2.8Mb
    lib          5.6Mb
```

**Review by gadenbuie — APPROVED** [review]
Looks great!

Would the change in `sass::read_gfont_url()` affect thematic? Asking because [these error seem possibly related](https://rstudio.github.io/shinycoreci/results/2024/03/11/#301-bs-themes).

**Comment by cpsievert** [comment]
> Would the change in sass::read_gfont_url() affect thematic? Asking because [these error seem possibly related](https://rstudio.github.io/shinycoreci/results/2024/03/11/#301-bs-themes).

No, thematic has [its own standalone gfont logic that seems to always uses `ttf`](https://github.com/rstudio/thematic/blob/b7ec742fefd176977eff5be721b62ff8ca96f386/R/gfonts.R#L30) since (I think?) that's more widely supported by `{systemfonts}`/`{sysfonts}`/etc

**Comment by fernandoroa-ss** [comment]
Is this Windows problem related?

Only in Windows the font is not available for a shiny app, with errors:

Screenshot 2024-07-27 085204

The workaround (for windows) is to add the `tags$head ...` while in Linux, the `bs_theme...` alone, works fine

```
    tags$head(
      tags$link(
        rel = "stylesheet",
        href = "https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap"
      )
    ),
    theme = bs_theme(
      version = "5", bootswatch = "flatly",
      base_font = font_google("Oswald"),
      heading_font = font_google("Oswald")
    ),
```

I don't know if this related to the use of `http` instead of `https`

**Pull request merged**
